### ISSUE TITLE
Scan files and and recognize ID3 genre numbers

### ISSUE THREAD

**Issue by guddl** [Rello/audioplayer#108]
It would be nice, if the file scan would note the genre numbers and fill the genre accordingly.

When you set the "TCON (Content type)" of an mp3 file e.g. to 183 then it should be recognized as an "Audiobook" in the nextcloud-audioplayer

Under Linux you can set this via: 

<pre>id3tag --genre=183 test.mp3</pre>

### ID Info 

<pre>
*** Tag information for test.mp3
=== TSSE (Software/Hardware and settings used for encoding): Logic Pro 7.2.3
=== TIT2 (Title/songname/content description): Test MP3
=== TPE1 (Lead performer(s)/Soloist(s)): Hans Mustermann
=== TYER (Year): 2016
=== TRCK (Track number/Position in set): 01
=== TCON (Content type): 183
*** mp3 info
MPEG1/layer III
Bitrate: 160KBps
Frequency: 44KHz
</pre>

You can find an official list of the "numbers" on wikipedia: 
https://de.wikipedia.org/wiki/Liste_der_ID3v1-Genres

**Comment by Rello** [comment]
Hello @guddl 
thank you for your request.

I see some issues here:
- The genre ID is only ID3v1 - the scanner is using v2 because this is the most common
- The ID3 editor of Audio Player only works for v2
- The genres are not language dependent
- The number form v1 would need to be treated as a default in case no genre in v2 is given. This would reduce the scanning speed of AP

unfortunately I don´t see the big need to justify the efforts for this deep modification.
sorry for that

**Comment by guddl** [comment]
Okay - No Problem. I will fix my MP3s ;-)
