### ISSUE TITLE
Configure multiple scan locations

### ISSUE THREAD

**Issue by oguelich** [Rello/audioplayer#114]
### Expected behavior
Select multiple scan locations in personal user settings for Audio Player. Only these configured scan locations will be considered during the scan.

### Actual behavior
In personal user settings it is possible to set a single directory (or whole user directory) that will be scanned. If you have a big folder structure and audio files are distributed in different folders you need to choose the full user directory scan and you need to exclude folders not relevant for scanning by adding a ".noaudio"-file to each folder. Recursive scanning of all folders takes more time than scan specified locations only.

### Steps to reproduce the behavior
1. Open personal user settings and make sure that no scan location is specified for audio player
2. Setup a big folder structure and distribute audio files through different folders, exclude some folders through a ".noaudio"-file.
3. Start a file scan and monitor scan time / load

### Possible solution (optional)
In personal user settings create a possibility to configure additional scan locations for audio player.

**Comment by Rello** [comment]
Hello,
Thank you for your request. 

The way the scanner works does not make any difference between one root or several selected folders - its only retrieving relevant mimetypes from the filecache. 
It would even make the whole process slower and increase te database operations in that case. 

.noaudio should only be used for folders that include specific audio files which you do not want. 

It is not helpfull to reduce the number of recursive scans because this is not how the filecache works. 

E.g. One music folder with 1 audio file and one document folder with 10.000 pdfs. 
Excluding documents or selecting music only would not make any difference at all for scanning performance

Does this help you with your concerns?
Changeing the coding of the scanner would involve a lot of testing across all platforms/include&exclude combinations and the usecase is very limited in my opinion

Let me know...
