### ISSUE TITLE
ID3 Tag changes (album) not reflected after rescan of Library

### ISSUE THREAD

**Issue by youphyun** [Rello/audioplayer#117]
### Expected behavior
Changes to id3 tag values (album) are visible in the main UI after rescan.
To me this looks similar to: https://github.com/Rello/audioplayer/issues/15 but I think this is a new issue.

### Actual behavior
Changes to the Album id3 tag are not visible in the music library after rescan.

### Steps to reproduce the behavior
1. Upload a few mp3 files with an incorrect album name using the Desktop client
2. Fix the album name on your local drive for a few files, so the files are re-uploaded with the fixed id3 album tag values
3. Notice that there are no changes to the albums in the main view
4. Select the fixed mp3 file and select the edit (pen) icon
5. Notice that the fixed id3 value is visible here or the field is blank because it does not match with the database.

### Possible solution (optional)
- Make the same edit in the online UI and/or pick the correct album solves the issue.

### Server configuration
**Web server:** Apache 5.6.28
**Database:**  mysql
**PHP version:** 5.6.28
**ownCloud/Nextcloud version:** Nextcloud 11.0.0 (stable)
**Updated from an older ownCloud/Nextcloud or fresh install:** Updated from owncloud and since first nextCloud release
**Audio Player version:** 1.4.0
**Where did you install Audio Player from:** nextCloud release
**Are you using encryption:** yes (https)
### Client configuration
**Operating system:** Windows 8.1 with Opera

**Comment by Rello** [comment]
Hallo,

thank you for your information.
I have some more questions just to understand the issue:

when you uploaded a new file, did you delete the library and then rescanned everything?
because changing the file locally will not be reflected until the library is actually cleared.

What could actually be the case is that the editor (and only this) is showing the locally changed album because it reads the data from the actual file and not the database. I need to test.

let me know for question one!
thank you

**Comment by youphyun** [comment]
I have not reset the library. Thats will definitely help to refresh the id3 tags. Thanks for the resolution. However I must note that it is not ideal with a music library with more then 3000 files. To make changes visible to the id3 tag of a few files the whole library need to be rebuild.

![000734_2017-01-14 22_07_13](https://cloud.githubusercontent.com/assets/12627719/21958125/154d6cfe-daa6-11e6-85b3-6e4622b931c3.png)

**Comment by Rello** [comment]
Hello,
the problem is, that the audio player can never recognize any local change to a file. If you would delete the file and upload it again, it would receive a new unique file-id in the file-cache.

The old one would be removed automatically at the next AP-start and just the new one would be found by restarting the scan.
Alternatively just use the ID3 editor of AP.

would the delete (in NC) and re-upload be an option?
From AP-side I don´t see an possibility to catch this issue at the moment

**Comment by youphyun** [comment]
Yes this will work. Thanks a lot for all help.

**Comment by Rello** [comment]
Hello @joephein ,
while fixing another bug I had an idea - perhaps you can give it a try and let me know.

When you open the ID3 Editor it will read the current ID3 tags from the file - not the database!
this might be the feature which could help (in case you remember which files you changed).
- Go to the file 
- open the Editor with the pen-icon
- save it right away

this should actually update the DB with the current setting and might give you a workaround.

let me know...

**Comment by youphyun** [comment]
Yes this indeed works. The new values in the uploaded file are loaded in the ID3 editor and upon save the changes are also visible in the UI.
