### ISSUE TITLE
No scan with a external storage

### ISSUE THREAD

**Issue by godemptiness** [Rello/audioplayer#129]
### Steps to reproduce the behavior
1. No scan with a external storage
2. If I see the files before in the directory, it will scan them and it works
3. But it's a long way around

### Server configuration
**Operating system**:
Debian

**Web server:**
apache

**Database:**
Mysql

**PHP version:**
7

**ownCloud/Nextcloud version:** (see `/status.php`)
9.1.3

**Updated from an older ownCloud/Nextcloud or fresh install:**

**Audio Player version:** (see `/settings/apps`)
1.4.1

**Where did you install Audio Player from:**
owncloud app

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
local and the local is in NFS

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**

**Browser:**

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
Insert your ownCloud/Nextcloud log here
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
Insert your browser log here
```
</details>

**Comment by Rello** [comment]
Hello,
I am not sure about your 
"If I see the files before in the directory, it will scan them and it works"

I just extended the wiki documentation here as the question repeats:
https://github.com/rello/audioplayer/wiki/specific-media-folder#external-storage
let me know if it answers your question

**External Storage**
Audio Player does not search for titles on file level.
Only these files can be indexed, which are already "known" to oC/Nc (indexed in the _filecache table; because of the mimetype filter required).
If a new external storage is connected, either the folders need to be navigated once, or `occ files:scan` needs to be executed to populate all files.

*Attention: * WebDAV is not recommended to to performance limitations.

**Comment by godemptiness** [comment]
OK. I started a scan. My problem should be this. Sorry for this issues.
