### ISSUE TITLE
playing music in the background

### ISSUE THREAD

**Issue by MG2R** [Rello/audioplayer#146]
I'm not sure if this is within the technical possibilities of the current Nextcloud App framework, but it would be nice if I could start playing music in the Audio Player app and then just use Nextcloud without the playback stopping. Right now I have to open multiple tabs to play music and browse files.

Again, I don't know if it's actually possible, but it would be a very nice addition.

**Comment by Rello** [comment]
Hello,
unfortunately this is not possible. every bigger request to NC triggers a reload of the whole page.
e.g. moving between different apps because they are not handled as simple "ajax" statements.

And as the player-stream is tied to the current screen session, it would be interrupted immediately.
