### ISSUE TITLE
Libre.fm/Last.fm integration

### ISSUE THREAD

**Issue by aairey** [Rello/audioplayer#148]
It would be nice to have last.fm audio scrobbling integration into the audioplayer.

**Comment by Rello** [comment]
Hello @aairey ,
I am not completely sure what is meant by this.

if it is related adding streaming functionality (adding online urls) its on our backlog already (#31).
if its related to adding some kind of api integration to a webservice, it is not in our focus.
AP is a pure player and we will not put efforts in external integration which would require a lot of testing and dependencies to external updates/maintenance.

if something like this is required, it could be developed as an add-on to AP. but thats not on our list right now. we don´t have the resources for something that complex.

thank you...

**Comment by aairey** [comment]
I don't know if it is but, isn't the code from Subsonic/Madsonic available
and reusable?

**Comment by Rello** [comment]
Hello,
Dont know. Sounds like a complete other mediaplayer. No relation to AP. 

Dond know if anyone can/would create a new app based on this.

**Comment by aairey** [comment]
Sorry my previous reply was somewhat out of context.
Thought it was about a different issue.

Last.fm and Libre.fm are audioscrobblers. They keep track of what you listen to.
Here are some [docs](http://www.last.fm/api/scrobbling) on the Last.fm API, which might help.

And [here ](http://www.last.fm/api/downloads)are some examples.
Could you reopen the issue, or at leas re-consider adding it to the roadmap?

edit: the JS link is broken, [this](https://github.com/fxb/javascript-last.fm-api) is the github repo.
Unfortunately the code does not support scrobbling yet ...

**Comment by Rello** [comment]
Hello,
A little provocativ question: why run a private cloud and then push information to the public again? ;-)

Now I understood your idea. 
Even so it sounds doable, it will currently not be implemented because the use case is very limited to some users. 

I could imagine implement notification hooks so add-on apps could connect to them. 
But as part of core AP it does not make much sense. 

Implement the API; API Key storing in NC; API error handling and notifications to the user; maintain API for every update of AP; monitor Last.fm for updates and maintein AP; ....

Quite some task for a limited amount of users. Due to our limited resources on the project, we will focus on more mainstream features like FLAC or m3u first

But feel free to step in ;-)
