### ISSUE TITLE
Issues with Mobile Safari on iOS

### ISSUE THREAD

**Issue by a1ex4** [Rello/audioplayer#167]
### Current behavior
* When playing an album and the song is over, it should begin to play the next song but that doesn't happen when the phone is locked.

* Adding the player to the home screen from Safari creates a nice little "app" on the springboard, but when accessing the player from this app and the locking/exiting the app the playback is paused.

* Metadatas such as artist, song name are not passed to the global iOS music player, so only the direct url is displayed on the lockscreen/control center.

Edit : also being able to use the iOS controls (play, pause, next, previous...) would be great.

### Steps to reproduce the behavior
1. Log in your Nextcloud server using Safari and go to the player app
2. Play a song in a list, lock the phone and wait for it to be over -> playback is stopped at the end
3. Add the page to the home sceen
4. Launch the new app from the home screen and play a song, then lock the phone -> playback is stopped

### Possible solution (optional)

I don't know how much these issues depends on how iOS/Safari are made, hopefully a workaround can be found.

 Thanks!

**Comment by Rello** [comment]
Hello @likeitneverwentaway 

I know about this requirement - it was bothering myself already for some time.
But unfortunately there is no solution to this.

Providing additional data to the lock screen in iOS (and also Android) is only possible via native apps.
Web apps don´t have access to the classes (keyword MPNow​Playing​Info​Center). Same applies for the media controls.

sorry

**Comment by Rello** [comment]
1. Log in your Nextcloud server using Safari and go to the player app
2. Play a song in a list, lock the phone and wait for it to be over -> playback is stopped at the end
3. Add the page to the home sceen
4. Launch the new app from the home screen and play a song, then lock the phone -> playback is stopped

**regarding 2**: when the song is started, the stream is handed over to the browser API which is taking care of the playback. When the stream is finished, the javascript of the Audio Player needs to get the next song and pass it to the API. But when the screen is locked, no JS is being processed to my knowledge (security and battery reasons)

**regarding 4**: I am not sure here, but due to the home-screen I think the website is treated as an app. And apps are closed/stopped upon exiting. Unless they are native and programmed differently

**Comment by Hk1020** [comment]
I've got an idea for a workaround. Don't know if it'll work but deliver all album songs as a single m3u playlist. I think iOS will play everything in it.

**Comment by ghost** [comment]
@Hk1020 We will test it when we implement the M3U feature. See #39 (backlog) and #31 (M3U).
