### ISSUE TITLE
Year field in Metadata Edit Windows too small

### ISSUE THREAD

**Issue by DiGGeR2** [Rello/audioplayer#221]
### Actual behavior
On editting Metadata the Year field display only 2.5/4 digits of the year

### Steps to reproduce the behavior
1. Edit Metadata of any MP3

### Possible solution (optional)
Enlarge the field

### Server configuration
**Nextcloud/ownCloud version:**
12.0.0

**Audio Player version:** (see `/settings/apps`)
 

### Client configuration
**Operating system:**
Windows 10

**Browser:**
Chrome 59

![capture](https://user-images.githubusercontent.com/1783500/27881118-cb4a627a-61c7-11e7-8a09-45cde9bfd638.PNG)

**Comment by ghost** [comment]
https://github.com/rello/audioplayer/wiki/development#focus

> The ID3 tag editor is an additional feature with no guarantee of completeness or error-free functionality.

The metadata editor is a part of the former MP3 Player app, which is currently not further developed. It is possible that the editor will be removed in a future version because it is currently only usable for ID3 tags. The development is focused on the player, not on the editor. It is also an option that the editor will be realized as an add-on to a future major release.
