### ISSUE TITLE
Rescan does not add new covers

### ISSUE THREAD

**Issue by Larsene** [Rello/audioplayer#239]
Rescan library does not update added cover.

1- add some MP3 albums in NC without covers (neither in folder, neither in mp3 tag)
2- launch AudioPlayer, then scan for new files
3- add cover.jpg for each folder
4- launch rescan tool. 

it won't update the added covers. You have to delete the entire database, then make a full rescan to add them. This could be very long.

**Comment by Rello** [comment]
Hello,
Thank you for reporting back to us.
This is an interesting case, which is not covered. AP can recognize new audio files, but not image files within an audio folder.
We will put this case to the backlog as we need to put the limited resources to the next features right now

**Comment by Larsene** [comment]
Thanks for your answer. I think this feature can improve the day to day AP use.

**Comment by Rello** [comment]
Hello,

due to the limited time available and the impact on the backend, unfortunately I can not proceed with this request.
The issue is, that AP is monitoring media mime-types.
To fulfil this requirement, I would need to monitor updated image mime-types (jpg & png; "folder" $ "cover" name) and hierarchically find their relation to possible audio titles.

The effort for this would take a an unnecessary load to all AP users' backends.

The workaround for this would be to change the corresponding title in the files app (e.g. add a space to the name and remove it). This should update the change-date of the file which would then make the scanner re-access it.
