### ISSUE TITLE
Settings button hides last entry in list

### ISSUE THREAD

**Issue by bretzel15** [Rello/audioplayer#262]
### Expected behavior
In album view or artist view, I can select the required album/artist from the list on the left.

### Actual behavior
The last entry of album/entry in this list is hidden by the "settings" button in the lower left corner.

### Steps to reproduce the behavior
1. is just there

### Possible solution (optional)
Maybe define the settings button not as overlay or restrict the area of the scroll list.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** php 7

**Nextcloud/ownCloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Audio Player version:** 2.2.1

**Where did you install Audio Player from:** from the integrated App repository

**Are you using external storage, if yes which one:**  local

**Are you using encryption:** no

### Client configuration
**Operating system:** Ubuntu 16.04

**Browser:** Firefox 57.0.1

**Comment by Rello** [comment]
Hello,
I can not reproduce the error.
when does it occur? the only instance would be if the settings are open. on all other occasions, the scrolling works.
![screen shot 2017-12-21 at 20 24 36](https://user-images.githubusercontent.com/13385119/34271570-1748bc36-e68d-11e7-8642-4d977580d109.png)

do you have a screenshot for us?
thank you

**Comment by ghost** [comment]
@bretzel15 `11.0.2` is an 8 month old version of Nextcloud. Please update at least to the latest release of the 11 branch (`11.0.6`) or make an upgrade to Nextcloud 12. After the release of Nextcloud 13 the 11 branch goes to _End of Life_ and also the Audio Player will no longer support this branch.
I close this issue because we cannot reproduce the behavior you described. Feel free to post a screenshot of the sidebar with opened settings panel.
