### ISSUE TITLE
Audioplayer CSS is breaking NC13 files action menu

### ISSUE THREAD

**Issue by juliusknorr** [Rello/audioplayer#264]
The following CSS rules from style.css is breaking the position of the file action menu with Nextcloud 13:

```
.fileActionsMenu {
    margin-top: 30px;
    margin-right: 5px;
    padding-bottom: 15px;
    top: unset;
}
```

![bildschirmfoto vom 2018-01-03 16-44-44](https://user-images.githubusercontent.com/3404133/34527306-75bd633a-f0a5-11e7-8578-6d79d85ed65d.png)

**Comment by ghost** [comment]
@juliushaertl Thanks for reporting this issue! This also affects Nextcloud 12.

**Comment by Rello** [comment]
interesting that it was not recognised yet.

the issue is, that the AP css is loaded in the files-app without being required at all.
will fix
https://github.com/Rello/audioplayer/blob/master/appinfo/app.php#L23

@juliushaertl do you have an idea on how to distinguish between files app and share-screen in a proper way to inject the files more focused?

**Comment by juliusknorr** [comment]
@Rello files and files_sharing have events for additional scripts that can also be used for styles:

See https://github.com/nextcloud/richdocuments/blob/master/appinfo/app.php#L37-L51 for example.
