### ISSUE TITLE
Multiple albums with the same name

### ISSUE THREAD

**Issue by eleksnell** [Rello/audioplayer#271]
### Expected behavior

Adding two albums with the same album name does not mix the two albums together.

### Actual behavior
Adding two albums with the same name creates one entry with songs of both albums mixed together. Take for example "St. Matthew Passion BWV 244" from Karl Richter (1980) and "St. Matthew Passion BWV 244" from Helmuth Rilling (1994).

### Steps to reproduce the behavior
1. Buy and rip two albums with the same name
2. Upload both albums in their respective directories
3. Re-scan audio player library

### Possible solution
Use more meta information besides just the album title to define album entries.

Note that one album could very much consist of multiple directories (for example 3 disks for the St. Matthew Passion).

**Comment by ghost** [comment]
> Note that one album could very much consist of multiple directories (for example 3 disks for the St. Matthew Passion).

For this, Audio Player take the `DISCNUMBER` tag into account.

---

Until we find a good solution, you can play a folder in the Audio Player.

**Comment by eleksnell** [comment]
Unfortunately, the folder view seems to have the same issue: The names are Disk_01, Disk_02 and Disk_03 and files of both albums are shown in each folder. From my perspective, it would make more sense to use something like a hash of the full path as unique ID for each folder/album.

**Comment by Maikewng** [comment]
I am affected by the same problem. For common album names such as "Greatest Hits" the immediate thought would be to use the album artist to determine the separation between different albums, but that's not always the case (just think about a Jazz collection of "Greatest Hits" of different artists).
Because of this, I suggest to take into account the belonging folder to make the distinction which is simple and straightforward.
For the case encountered by @eleksnell I would then suggest to put all the files in a single folder and rename the tracks to something like, for example "3-02 Tell Me Baby.opus". I already employ this naming scheme (the default with MusicBrainz Picard) as it's highly compatible with other music management softwares.

EDIT: If you feel like it can be quite a controversial detection scheme, it can be considered as an optional feature: "Folders are albums"

**Comment by Rello** [comment]
I will look at this because its a valid case...

**Comment by Rello** [comment]
ready for testing

the scan will recognise different folders and save the album separately. separate cover art files will be processed accordingly.
the full path is not shown yet in the AP. This will perhaps be implemented later

**Comment by eleksnell** [comment]
I am testing it right now and it seems to work as expected without issues. Thank you!

**Comment by ghost** [comment]
> the full path is not shown yet in the AP. This will perhaps be implemented later

The full path is now displayed in the new sidebar below the cover.

**Comment by ghost** [comment]
> For the case encountered by @eleksnell I would then suggest to put all the files in a single folder and rename the tracks to something like, for example "3-02 Tell Me Baby.opus".

`Disc-Track Something` is the appropriate name scheme for albums with more than one disc, to prevent unnecessary albums in navigation and lists. A separate folder creates an additional album now.

I'm using this for storing different versions of the same album with different audio channels (2/6ch), bits per sample (16/20/24bit), and sample rates (44.1/48/96kHz).
