### ISSUE TITLE
Group folder/shared index support

### ISSUE THREAD

**Issue by psy-q** [Rello/audioplayer#278]
In Nextcloud 13, group folders are available, making it easy to share an audio collection between people. But it seems that Audio Player prepares one index per user instead of creating the index for the group folder only once and sharing it between all users.

This way, users are pretty much always out of sync as files are added and removed from the group folder.

**Comment by cal0pteryx** [comment]
I would highly anticipate a shared music database. Scanning the library per user (4-6 h each) makes this process very time consuming (and unnecessary when every user has access to the folder). This would be a huge improvement!

**Comment by Rello** [comment]
Hello,
we will look into the details of the new functionality.

At the moment it only work by sharing the corresponding folder directly and doing a scan when new files are there.
But the user should be notified because AP recognises new files. So the first scan (could be done with occ) is the one taking longer.

we will check group folders anyway....

**Comment by jauling** [comment]
Hey @psy-q I've been sharing folders with groups since Nextcloud 12. Are you possibly talking about another feature?

**Comment by psy-q** [comment]
The sharing itself works, but each user needs its own index, so with my collection (around 80000 songs) it takes several hours for each user. If the index were shared, it would only take several hours once, and then each incremental reindex of new items could also be shared between users.

**Comment by Rello** [comment]
I can not follow this request due to very limited time available at the moment.
sorry
