### ISSUE TITLE
remember playback position between sessions

### ISSUE THREAD

**Issue by personal-assembly-required** [Rello/audioplayer#288]
do you think it is possible with you app/setup and where about in the code base would those bits so i might have a  hand at adding them ?

not really an issue more of a feature request so request for information

**Comment by Rello** [comment]
Hello,
I am looking at this for the upcoming release...

**Comment by Rello** [comment]
@mcorrigan
@personal-assembly-required

current implementation workflow:
- every 10 seconds, the position is saved (not more due to backend load)
- when audioplayer is reopened, the last played title will be selected (already existing)
- when the last played title is started, the last position will be used
- when another title is started, the position will be reset
- the position is only stored for the LAST played title

what are your opinions?

**Comment by Rello** [comment]
due to the dependencies, this currently only works in the AP app itself. not in the sharing screen or files app

**Comment by mcorrigan** [comment]
@Rello I think that would work great! Thanks for working on this!

**Comment by Rello** [comment]
Version 2.11.0 was released

**Comment by Torenga** [comment]
Maybe this should be a separate issue, but it's directly related to this feature.

Remembering position and resuming doesn't work on my NC19.0.4 - Audio Player 2.12.0 setup. Tried on both FF/Chromium, with MP3 and OPUS. Unless there's a user error on my part ofc.

When exiting the AP and reopening, the player is empty

It's a great sounding feature that I hope I can get help to get working.

>current implementation workflow: The position is only stored for the LAST played title

If possible I would like per track position. I switch between several audiobooks (each book is a single file) and long-runtime podcasts, having a reset every time I switch isn't ideal for my use case.
