### ISSUE TITLE
API endpoints for mobile app consumption

### ISSUE THREAD

**Issue by kevincianfarini** [Rello/audioplayer#314]
I've personally never worked with PHP so if I'm missing something, could you please point me in the right direction? 

I think this NextCloud add on has the potential to replace Google Play Music and similar services for a lot of people who want to self host their music library. That being said, a native app for a mobile platform provides a lot of benefits that a web player wouldn't be able to accomplish. The most important of these features would be local track caching on client devices. 

If there exists a set of API endpoints to make this possible, I would be more than willing to dip my toes in a native mobile companion app for Android.

**Comment by Rello** [comment]
Hello,
thank you for this interesting request. I was looking into the issue when locking the screen of your mobile while playing. Only the current song is being finished then - not the current playlist for example. This is because of the JS in the background which is stopped for energy reasons.

a workaround would be to transmit a playlistfile to the client - but this was not followed further.

Regarding your request: I don´t know about the authentication backend of the native app. But if you are logged on in your NC instance you should perhaps be able already to access some of the standard APIs, which Ajax is already using?

`https://testserver/owncloud/apps/audioplayer/getcategory?category=Album`

If not, I saw some public API endpoints in other Apps I would need to search for.

How far do you want to go?
Just getting the META information visualised in a native app and then still stream from the backend? This could be better achieved by using the webdav-urls which AP could also deliver.

let me know about your idea.
thank you...

**Comment by Rello** [comment]
Hello @kevincianfarini 
did you look into this already? did you try to access a URL already?
If not possible, the @CORS header seems to be the way forward to analyse

let me know if you are still onto this topic!

**Comment by Rello** [comment]
Hello,
let me know if you still want to continue here. then I can reopen the issue....
