### ISSUE TITLE
Show broken files location when rescan.

### ISSUE THREAD

**Issue by terokorp** [Rello/audioplayer#320]
### Expected behavior
When rescanning files, it tells which file(s) are broken

### Actual behavior
But dosen't tell where that/those are

### Steps to reproduce the behavior
1. Add some broken files to subfolders
2. Rescan

### Possible solution (optional)
Add folder structure to error message like on "Duplicates found" list

### Server configuration
**Operating system:** Debian 9.4

**Web server:** Apache/2.4.25 (Debian)

**Database:** 10.2.16-MariaDB-10.2.16+maria~stretch

**PHP version:** PHP 7.1.18-1+0~20180611145904.18+stretch~1.gbp2b32f6

**Nextcloud/ownCloud version:** Nextcloud 13.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Audio Player version:**  2.3.1

**Where did you install Audio Player from?** NC App Store

**Are you using external storage? If yes, which one:** smb

**Are you using encryption?** no

**Have you activated other multimedia apps?** No

**Audio Player media folder:** username/Music/

### Client configuration
**Operating system: Windows 10

**Browser: Firefox 61.0.1

#### Nextcloud/ownCloud log

irrelevant

**Comment by Rello** [comment]
Hello,

to find a really messed up file, this can only be analysed in `occ --debug`.
Duplicate and error files (where the ID3 Parser can not extract valid information) should both be shown already. 
But when there is another serious issue and the php engine fails, you will see an error log in you php `error.log` and within the `occ` you can see the last file being processed to cause that error.

I can not catch php errors because they fail the hard way.
did you find the error-file using occ or error.log?

Regards...
