### ISSUE TITLE
FR: Old design when playing from anonymous share - As option in the settings

### ISSUE THREAD

**Issue by Huster-at-github** [Rello/audioplayer#323]
Can I have please the old design as an option selectable?

**Current version (0.7.0):**
On the top there is a - very short - scroll bar to fast-forward.
![grafik](https://user-images.githubusercontent.com/3857906/43023362-e25aedda-8c6a-11e8-90f3-3abc9765b25f.png)

**Former version:**
There was a cycle which used half of the mobile screen - very comfortable to fast-forward!  👍 

**Background:**
Mostly playing long tracks (1h - 6h). Fast-forwarding in this kind of tracks is not possible (exactly) with the new design.

**Screenshot former version:**
No more available.  :-(

**Comment by Huster-at-github** [comment]
Found the former design:

![grafik](https://user-images.githubusercontent.com/3857906/43027662-f8c995f6-8c7b-11e8-9dd3-099619fd9665.png)

**Comment by Rello** [comment]
Hello,
this is an issue. need to look at it.
the old 360 stuff was removed on purpose because it brought a lot of js/css overhead with it.

What you see is the stock player of the share screen of NC, wich was introduced with 13. before there was none. So when this was changed, there were two players on top of each other.
The old tweak would mean to hack the NC-standard out of the sharing screen and overwrite with the 360.
I need to think about this. not sure if there will be a solution

**Comment by Rello** [comment]
Hello,
I am closing this because my unpaid time is limited and I have to focus on the topics that I need for myself.

thank you...
