### ISSUE TITLE
Question / Feature: "Android Application based on audioplayer"

### ISSUE THREAD

**Issue by waltercool** [Rello/audioplayer#332]
I'm developing an opensource Android App based on audioplayer APIs (to replace Google Play Music)

Want to know if API are gonna be stable endpoints, or may change with time. Do you plan to keep some stable APIs? I will use endpoints just how are currently used for the music player.

Thanks.

**Comment by Rello** [comment]
Hello,
thank you for your feedback.
They should be stable - I don´t see any change to the existing ones besides possible bugfixes in the backend.

do you have more information on your work? github?
I would like to know what you are doing - would be a pretty nice feature to refer to.

Also: if you require a change to an API like e.g. security headers or so, lets talk about it...

**Comment by waltercool** [comment]
I just started yesterday after analyzing all requirements, I currently have nothing functional, just some login interfaces.

Let me ping you as soon I have something functional. This application will use:
- List songs (download list from getCategory /getCategoryItems)
- Play (from getAudioStream)
- Download for offline use (???)
- Starred (setfavorite)

Any ideas for download songs, except filemanager?

**Comment by Rello** [comment]
ok, I see

question is what you want to do - online or offline?

you refer to the "Play" via getAudioStream. I am not sure if this is the way to go, because this is used to stream a file to the js-player of soundmanager.
Did you look at webdav? I was thinking to move to stock html5 `<audio>` tags using webdav some time. if you share an audio file, you can see that NC is using this already in the share screen.

I think it might be better way to go because then the app can do all the streaming/buffering part itself.
and when you have webdav, you should be able to setup a download on top of that logic.

what do you think?

**Comment by waltercool** [comment]
My idea is replicate basic functionality of Google Play Music, so both of them, defaults to online play, with optional offline play

Oh I see, just checked getAudioStream details, and it looks like you provide the whole song as base64. It could work for downloading songs. I'm wrong?

There is some possibility to create rtsp from backend? So both html5 and android version could enjoy an easy management of stop/play/seek functions.

Under current limitations, I think we should work as offline player (download to play), and then analyze a proper streaming option. Basically using getCategory for interface and download files with webdav as you said.

Do you agree?

**Comment by Rello** [comment]
> Oh I see, just checked getAudioStream details, and it looks like you provide the whole song as base64. It could work for downloading songs. I'm wrong?

I am not sure if will work reliably because it is doing quite some packaging/partial transmit.
wouldn´t it be easier to create the webdav link? 
by using the fileId form getCategoryItems you should be able to create the link like `https://testpi2/nextcloud/f/2880`

I think it might be easier to handle within your app.
RTSP sounds a little too much because - if I am not wrong - this is a server thing incl. dedicated ports

**Comment by Rello** [comment]
any update?

**Comment by waltercool** [comment]
Still on very alpha stages, will share a gitlab link as soon I upload an alpha version.

Past week been at vacations, so I didn't made any progress except talking with an ux designer for a prototype.

Hope I can upload an early stage version this week.

**Comment by Rello** [comment]
I cant test it anyway because I don´t have any androids.
I would like to know which information from which interfaces you are using. perhaps I can include specific ones (smaller/quicker) into the next release.

e.g. the getCategoryItems has the covers in. if you don´t need them, we could speed up the delivery drastically

**Comment by waltercool** [comment]
OK for now I pushed a very early version here: https://gitlab.com/waltercool/nextcloud_musicplayer

For now, I will use getCategory / getCategoryItems only.

Under a first alpha I will list categories, then songs. Download only, then play.
I think under a second alpha I will try to use covers and get UI nicer.
Under a third alpha we may guess how to stream music (maybe just cache download and play?)

For now I want to keep basic functionality working out (first alpha), then we might figure out secondary stuff.

Question, do I have some way to get current audioplayer version? Just to make sure about limitations under certain versions (like API)

**Comment by waltercool** [comment]
Uhm, let me change the project name, I don't think using nextcloud name would be okay

**Comment by Rello** [comment]
hey,
naming is always the question - it took me weeks.
there is the repo and the app name itself.

will you base this on Audio Player backend or want to go for others also? if you go for Audio Player - which would be pretty nice - you would have some choices of combination.

- Cloud  (I think you would  keep it generic because AP also works on ownCloud?)
- Audio
- Music
- Audio Player
- Android
- ...
- 

I don´t have an audioplayer version via api - but I could create one for the next release. no problem. at the moment you should be fine because the mentioned apis are not planned to change.

**Comment by waltercool** [comment]
I just finished renaming it to "Cloud Music" for now https://gitlab.com/waltercool/cloudmusic, I think is an acceptable name for now (until I discover someone owns copyrights of that name). It took me some minutes also to find a name, but I still need to find if I'm not breaking any copyright.

I wouldn't go for Audio Player because is too generic to find at Play Store / F-Droid / other store. At ownCloud there are no others sharing the same name (I reviewed Google Play, and there is no Cloud Music app)

About API, yeah, I mean, if you are going to create new APIs in future, I need to know if the current version has the minimal endpoints, is just to display some warning if Audioplayer is outdated, but Cloud Player is recent.

**Comment by clawoflight** [comment]
Just a quick question - did you guys consider simply implementing the Ampache protocol, like the old owncloud music app did? That would give instant support for many apps, e.g. foobar2000, Amarok, VLC, Power Ampache, etc.

There's also subsonic, which again is supported by many clients already.

**Comment by Rello** [comment]
Hello @clawoflight 
no, we will not build an interface directly into Audio Player because it requires too much maintenance and creates to many dependencies and testing efforts for every release.

But features like this make sense to be delivered as an Add-on - so a second app which depends on the APP backend/database.
This is the same approach as with the ID3 Editor. It was separated out of AP (but not released as not a real usecase obviously)

So if you have any Idea in protocols like this, it should be relatively simple to create an app based on the AP backend.
Feed free to initiate one :-)
You will have my support

**Comment by Rello** [comment]
any update on this?

**Comment by waltercool** [comment]
> any update on this?

Hey, very sorry for my delay, been a bit busy this last month. Been thinking to change my route and create AudioPlayer support at some already-existing opensource media player, just to avoid reinventing the wheel.

I tried some of them, but still not convinced. Just to know, do you know some good opensource audio player? If people already made a lot of effort at some music player, why just not support NextCloud using AudioPlayer database and API

**Comment by Rello** [comment]
continuing in one issue to collect and document all requirements: #365
