### ISSUE TITLE
Local audio playback (on server's audiocard) and Chromecast playback

### ISSUE THREAD

**Issue by anklimov** [Rello/audioplayer#341]
Hello,
It might be very suitable to allow playing of music locally (on USB soundcard, connected to the server) instead streaming to web client and/or Chromecast device (like Google Home assistant, using appropriate API)

Is somebody share same expectations?

**Comment by Rello** [comment]
hello,
I am currently working on the SONOS integration
https://github.com/Rello/audioplayer/issues/331

but for local playback - not sure how this should work because php would need to talk to whatever local sound/driver setup is being used.
any technical background available? if not, I will need to close the request

**Comment by anklimov** [comment]
Sorry for late answer - It should be not a bug issue - on *nix based OS'es the best practice is to use external utilities (like aplay or vlc) to interact with sound subsystem
The best way to invoke some configurable "playscript" with appropriate parameters:
$1 - local path
$2- URL mapped filename
$3- command (play, pause)
$4- (optional) - position

PS
Another possible improvement - to integrate GoogleHome/Chromecast
