### ISSUE TITLE
Feature Request: Add cover art as blurred background image in songlist

### ISSUE THREAD

**Issue by Amr0d** [Rello/audioplayer#356]
It would be nice to have the cover art as a blurred background image instead of the blank space. With my limited css knowlegde I did something to show you in Chrome.

![2018-10-21](https://user-images.githubusercontent.com/26941455/47268171-c9d24980-d54d-11e8-977c-efe3a306a8dc.jpg)

The only thing I wasn't able to do was the `filter: blur(5px)` because it blurred everything including the text etc. 

Opacity could be reduced as well, so the whole thing is not to bright.

**Comment by Rello** [comment]
Hello,
interesting approach.
I will keep this open and will have a look it when starting work for the next version

thank you

**Comment by Rello** [comment]
Hello,
due to the lack of time involved here, I have to close this request.
I don´t know of any similarity like this in NC anywhere - and the app should behave consistent.
Additionally, I see a log of challenges with invisible letters due to similar background colors. it would be hard to read all information

thank you
