### ISSUE TITLE
Feature Request: Support of manyfold formatted Content

### ISSUE THREAD

**Issue by uwedisch** [Rello/audioplayer#358]
It would be very helpful if Audio-Player supports manyfold formats for an entry.

Example: It should be possible to have an album stored as *.flac and as *.mp3 files and to see two separate listing entries within the album itself. Example of Windows Media Player how this could be done (upper entry *.flac version, lower one *.mp3 version):

![grafik](https://user-images.githubusercontent.com/24267159/47754098-16c6c600-dc9a-11e8-8b13-c50cc8ddd813.png)

Current state: If an album is stored in two formats you see all files doubled within the album resulting in each song playing twice which is not wanted.

**Comment by Rello** [comment]
Hello,
if you name the albums the same, they will be grouped in the albums-view accordingly.
Technically there is no other possibility because the album is extracted out of the ID3 tags. and whatever belongs together, will be seen as the same album.
Without this, ID3 could not find related titles across locations.
I would not know how to fix it.

the only area where you will find these separated is with the "folders" category.

thank you for your request...
