### ISSUE TITLE
Shuffle: play tracks only once

### ISSUE THREAD

**Issue by AmonBune** [Rello/audioplayer#361]
### Expected behavior
The Shuffle function shuffles all displayed tracks in a different order.

### Actual behavior
The Shuffle function sometimes plays tracks multiple times, it's really "random" now, as it just plays any track it wants, without checking if it was already played before.

### Steps to reproduce the behavior
1. Select a folder
2. Play
3. Enable shuffle

This was tested on the **Nextcloud 15.0.0 RC1**, the currently latest **beta version**, using PHP 7.0.32

**Comment by Rello** [comment]
Hello,
interesting find. this is caused by the `getNext` function to create a random sequence every time again
https://github.com/Rello/audioplayer/blob/master/js/bar-ui.js#L533

you are expecting that the shuffle only plays every title once and if at the end, the list will stop?
This would not work with the shuffle mode of the soundmanager2 backend because it relies on the displayed list.

I need to think about it. the only way I could think of is to change the player in that way, then when pressing the shuffle button in the playbar, the displayed playlist will be shuffled and displayed in a different sequence (similar to sorting via a click on a column header).

By this the list will be shuffled and the player will "just" play sequentially what being presented.

What is your opinion?

**Comment by AmonBune** [comment]
"you are expecting that the shuffle only plays every title once and if at the end, the list will stop?" - yes, that's my understanding of "shuffle the songs".

And the way you explained is exactly what I mean. Sort the current list of songs in a different order (make a copy of the actual list and shuffle that) and feed it to the player. On the front end, you would still have the original alphabetically sorted list.

**Comment by Rello** [comment]
https://github.com/scottschiller/SoundManager2/issues/189

**Comment by Rello** [comment]
Hello,
i am still thinking about this. your suggestion does not work because the frontend and "backend" list of the player itself need to be in sync.
It would actually require to store a play-history of IDs.
hmmmm

**Comment by Rello** [comment]
Hello @AmonBune 
actually it worked out easier than expected with the new html5-only backend.
will be included in the next release!

**Comment by Rello** [comment]
Version 2.11.0 was released
