### ISSUE TITLE
Audioplayer stuck on scanning folder

### ISSUE THREAD

**Issue by Blisk** [Rello/audioplayer#362]
### Expected behavior

Scan for audi files should scan to the last file
### Actual behavior
Scan for audio files never finish, it always stuck on some file.

### Steps to reproduce the behavior
1. start to scan files
2. it makes fev %
3. than it stuck

### Server configuration
**Operating system:**
centos 7.2

**Web server:**
apache

**Database:**
mariadb
**Nextcloud/ownCloud version:** (see `/status.php`)

nextcloud 14
**Audio Player version:** (see `/settings/apps`)

2.4.1
**Are you using external storage? If yes, which one:** `local/smb/sftp/...`

### Client configuration
**Operating system:**

**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Blisk** [comment]
No help?

**Comment by Rello** [comment]
Hello,
without any detail it is hard to tell.
there are several areas of failure: Server cache; php cache; defect files; limited ressources; missing php-smblibrary

- does it continue if you restart the scan after it stopped? 
- does it go for x titles further every scan?
- did you do an occ --debug scan already?

**Comment by Blisk** [comment]
Hi
No it doesn't continue, sometimes stops to scan when find some duplicate file, sometimes scan fev percent and than stop. How far it goes it is hard to tell because it goes so random. Sometimes 2% sometime 16%.
I have run occ scan files and it goes from start to end with no error

**Comment by Rello** [comment]
hello,
I will have a look. I am starting with the next batch of improvements and will have a look at the frontend scanner status updates

**Comment by Blisk** [comment]
Thank you.
Maybe you can considere to make this program more advanced and something like DJ station where people can play this music like DJ. And that advanced feature will cost fev Euros.

**Comment by Rello** [comment]
Hello,
i could reproduce your issue on one of my test instances.
there seems to be an issue with the cache in nextcloud. I will work out a solution

**Comment by Rello** [comment]
Testresult:
- [X] NC 15
- [X] oC 10

**Comment by Blisk** [comment]
I have donloaded latest version and tested it and it is the same.
Only now it stuck on the same song everytime.

**Comment by Rello** [comment]
hello,
I tested it in several setups and the scanner itself seems to work.
if it is stopping at the same file every time, there seems to be an issue with either one of the titles or the server setup
I don´t have any idea what else I could fix here, unless we get some meaningful logs...

**Comment by Blisk** [comment]
When I test it again it stuck on the same file, than I tested fed days later and it stuck on other file that day and so on.
Which logs I can provide to see what is wrong?

**Comment by Micdu70** [comment]
Hello there,
Scan always stuck on same file, here is the error log line:
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_audioplayer_tracks` (`user_id`,`title`,`number`,`artist_id`,`album_id`,`length`,`file_id`,`bitrate`,`mimetype`,`genre_id`,`year`,`folder_id`,`disc`,`composer`,`subtitle`,`isrc`,`copyright`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)' with params ["username", "\x41\x6d\x6f\x75\x72\x65\x75\x78\x20\x44\x65\x73\x20\x52\xea\x76\x65\x73", 1, 556, 642, "3:47", 9047, 1038688, "audio\/flac", 84, 2018, 2189, 1, "", "", "", ""]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xEAves' for column `username`.`oc_audioplayer_tracks`.`title` at row 1
--
```
Anyway, thanks for this nice app! 👍

**Comment by MaxGitHubAccount** [comment]
Hi @Rello,

I would ask you to re-open this issue.

I saw your app in the mastodon news for nextcloud 16 and thought it could be a nice alternative to the music app from owncloud. However I am stuck within the scanning.

**Expected behaviour**
In case the scan fails for a file, it is skipped to the next file. In case only one meta tag is corrupt (in the point of view of the application) the file is imported as good as possible.

**Observed behaviour**
Scanning via UI:
The scanning always stops at the exact same file after scanning about 250 files.
Scanning via console, for every file apart from these 250 it seems to throw this error:
"Error with getID3. Does not seem to be a valid audio file"

**Expected solution**
It seems that the exception / error handling is too invasive, I would prefer that in case one tag, or one name is not in the correct format as expected maybe the error tags this file as with an error and tells this in the log, but the file per se is imported with all the tags / meta info it can.

**Server configuration**

Operating system: Debian stretch latest updates

Web server: apache
Database: mariadb
nextcloud 15
Audio Player version: 2.6.1
php-getid3 version 1.9.12+dfsg-1
Are you using external storage? yes sftp at a local system

**Client configuration**

Operating system: Arch Linux Latest
Browser: Firefox

**Log**
via pm

**Comment by Rello** [comment]
hey,
further analysis showed that the scanner breaks when there is a corrupt art-work file in place.
unfortunately this is a php fatal error which is not handled in NC itself (I am using the stock image functionality) and can also not be handled. (The problem here is that we have no way to catch PHP fatal errors)

e.g. 
https://github.com/nextcloud/server/issues/11863
https://github.com/rullzer/previewgenerator/issues/27

in fact it should be just a warning as of GD version 2.2.5
but I am using that version and its still an error.
https://github.com/libgd/libgd/issues/419

no idea what to do here at the moment

**Comment by Rello** [comment]
I know changed the log entry sequence to get an indication of the failing image.

in occ -vv mode, it will first tell the image before processing
`Alternative album art: issue362/folder.jpg`

the scanner will fail right afterwards if there is a serious issue
`{"reqId":"32oJZwz6LeMjGo1K9XhP","level":3,"time":"2019-04-15T16:32:04+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"imagecreatefromstring(): gd-jpeg: JPEG library reports unrecoverable error: Unsupported marker type 0xfa at \/var\/www\/nextcloud\/lib\/private\/legacy\/image.php#645","userAgent":"--","version":"16.0.0.6"}`

so the last processed image needs to be removed
thats the only workaround for now

**Comment by Rello** [comment]
2.7.0 released
