### ISSUE TITLE
Feature: Folder tree view

### ISSUE THREAD

**Issue by roker** [Rello/audioplayer#374]
Current organization on my file system looks like this (and I believe most people are using something like this):

/music/Author/Album/Song

In folder view, the path is ignored and only Album folder is shown, which makes it quite useless. On the other side, other views are useless if you have a large collection of mixed songs (1 song file, 1 author, 1 album => 1000 mp3s, 1000 authors, 1000 albums)

It would be great if folder view wouldn't be a list but rather a tree.

**Comment by Rello** [comment]
Hello,

thank you for the suggestion. It could be quite interesting but would mean a very run-time intensive tree-calculation because it would need to read recursively the whole tree.

Unfortunately I don´t have resources to pull of such a big new feature. Despite >10.000 users, the support for the app is almost 0 in any direction.

I included it into the feature request list for later reference.
I can only suggest the search integration for the moment.

Thank you
