### ISSUE TITLE
Preview feature of audio files

### ISSUE THREAD

**Issue by bitking** [Rello/audioplayer#41]
Hi there,

When clicking an audio file in the owncloud file browser i hear music but there are no controls at all.
This is a hindrance because it keeps playing and i cant stop it unless i reload the webpage or start another app.

Can you please make basic audio controls for this? (play, pause)

**Comment by Rello** [comment]
Hello,
when a title is played, you will see a playing indicator in the icon of the file.
depending on the preview-icon it might be not very visible because it is currently grey (I will look at it to enhance the contrast).

but when klicking the title again, it will stop playing.

to show a more detailed player - I will put it on the feature request list.

**Comment by ghost** [comment]
> but when klicking the title again, it will stop playing.

This is a simple and acceptable solution, imho. This works in the mobile browser, too.

> to show a more detailed player

No need to overload the app. Please, keep it simple and fast.

**Comment by Rello** [comment]
> I will look at it to enhance the contrast

a ttf fonteset is used. a black border was added for additional contrast
![screen shot 2016-08-23 at 20 02 50](https://cloud.githubusercontent.com/assets/13385119/17919503/668578a8-69ce-11e6-9e2b-3870572dab9a.png)

**Comment by Rello** [comment]
changed to a more visible one
![screen shot 2016-08-24 at 16 28 01](https://cloud.githubusercontent.com/assets/13385119/17938636/1bd4398a-6a27-11e6-82e0-8364c488b708.png)
