### ISSUE TITLE
Deleting Music files

### ISSUE THREAD

**Issue by mmeinesz** [Rello/audioplayer#445]
This is a feature request.

I would like to be able to delete music files right out of the app "audio player" without moving to the main nextcould file browser. 

Reasion/Background: Most Audio Apps do not allow to delete the original audio files. Usually they only delete the db entry, so the audio file is invisible. However this leads to music in a library that the user does not enjoy and actually wants to get rid of. I am sure other users willl enjoy this feature as well.

**Comment by Rello** [comment]
Hello,
Thank you for your inquiry. 

This request is a little tricky to implement because AP is used for multi-users. 
So to enable a user deletion we would need to check it the user has the delete autorization himself, on the share, on the federation, on the external device...

Thats a lot to implement for this small use case

**Comment by mmeinesz** [comment]
Hi Rello,
Thanks for the quick answer.

So, that means that all users have the same rights to use the audio files. They all do not have the right to move or delete the files. Is there a way to mark the files, so they can be searched upon in the nextcloud file brower and then collectivly be deleted?

**Comment by Rello** [comment]
hello,
the only workaround I could think of is to use the favourite start. that can mark a file temporarily.
I don´t see anything else at the moment
