### ISSUE TITLE
Can't scan files library

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#448]
### Actual behavior
The scanning process starts and stops just like it was done, but only after some few files, not after several 100 files like it should do.

The main reason will be probabely "Invalid datetime format: 1366 Incorrect string value: '\\xFF\\xFE0' for column `nextcloud`.`oc_audioplayer_genre`.`name` at row 1..."

### Steps to reproduce the behavior
1. start scanning your library
2. 
3. 

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache 2

**Database:**
MariaDB

**Nextcloud/ownCloud version:** (see `/status.php`)
Version 16 and 17

**Audio Player version:** (see `/settings/apps`)
2.8.4

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
Yes, smb

### Client configuration
**Browser:**
Firefox 70.0.1

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here

```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```

```

</details>

**Comment by Rello** [comment]
Hello
Thats strange. The error indicates unicode contend - but this should have been caught by the scanner in some place. 

I will check

**Comment by ghost** [comment]
Is it somehow possible to see which file is the reason for the failure? I can't find any filenames like "*.mp3" in the logs.

**Comment by Rello** [comment]
thats really strange, because there is one central function, which should catch exactly this content
https://github.com/Rello/audioplayer/blob/master/lib/Controller/ScannerController.php#L685

could you try to scan with the occ command and -vv parameter?
e.g. `sudo -u www-data php occ audioplayer:scan username -vv`

This should then show you the last song in the list, that makes the scanner fail.
let me know if this helps. If you found it, please save the file. I would like to look at it.

regards...

**Comment by ghost** [comment]
After moving some files (the last one showing) and folders/album and moving them back again, I only get this output (after a list of already indexed files):

Final audio files to be processed: 579
Total stream files: 32
Checking stream files to be skipped
Final stream files to be processed: 0
Start processing of audio files
Audios found: 1
Duplicates found: 0
Written to library: 1
Albums found: 0
Errors: 0


But it is not showing which file would be the next one, the one it tries to read/scan.

Could you make a change in the app, so it shows the file which will be scanned next, not the one which have been scanned successfully?

**Comment by Rello** [comment]
Hello,
with -vvv it will be the maximum output in the log that you can get.
will display every title and every cover it is processing

**Comment by RobertZenz** [comment]
No, it doesn't. I have the same problem and the output, even with `-vvv`, looks like this for me:

```
Start scan for robert
Start processing of audio files
Scanned Folder: /robert/files/music
Total audio files: 3929
Checking audio files to be skipped
Final audio files to be processed: 3929
Total stream files: 1
Checking stream files to be skipped
Final stream files to be processed: 0
Start processing of audio files
Audios found: 1
Duplicates found: 0
Written to library: 1
Albums found: 0
Errors: 0
```

And nothing is added to my library. There are ~4k audio files (mp3, flac and ogg) in that directory tree, but what I actually want to be added is the playlist (pls) which resides in that directory and contains a list of all of these.

Can't we have a way to add a single file, additionally to the automatic scanning? So that we can say "yes, add exactly this file"?

**Comment by doobyd** [comment]
Hi,
I have run into the same problem recently. Even posted a new thread on owncloud central, because this problem looked for me like problem with new installation, which I have done recently. Also I have been using audioplayer app for more than year now and I did not supect any unwanted behavior.
I think that I have example of file, which causes the problem. I found a way to locate mp3 files, which is causing problem: in the same line of log as the error "Invalid datetime format: 1366....." there is at some point id, which points to directory, where the "broken" file is located (using phpmyadmin I found it in oc_filecache (or something like this) table the path to directory).
And I found workaround for that - using mp3tag simply save the same ID tags as in the source files. This changed only version of the tag saved to the file. With this modification I was able to "fix" my library. The problem was with ~5 files in over 10000 library. I was changing only files in the directory, which I determined using steps described above.
If it is desired I can share the file, which is causing the problem on my side for further investigation.

Best regards

**Comment by Rello** [comment]
Hello,

sorry to hear that you had such a big effort to fix the scanner. 
unfortunately if there is a hard php-error in the external getID3 library, its difficult for me to catch it. the scanner was hardened quite a lot already, but I am still dependent on correct files.

thank you for the feedback

**Comment by doobyd** [comment]
Forgot to mention - this file worked before without causing any problem. So there was a change somewhere: either in the external library or in the scanner, which introduced wrong behavior of the scanner.
When I know how the workaround there is no problem for me, but I can share the file just for your curiosity. So you can check on your side.
Is it possible that this error is connected with system configuration?

**Comment by Rello** [comment]
Hello @PalArt 
is the issue still existing or could you sort out the file causing the problem?
