### ISSUE TITLE
FLAC Support

### ISSUE THREAD

**Issue by microcreators** [Rello/audioplayer#45]
first of all, thank you very much for 1.1 - works great 👍 
and my small request is simple... flac support. although I'm not really sure how much you're dependant on this external players. 

one more thing. i noticed users have to refresh the list of albums, although it's all based on same, shared directories. any chance to have a an admin to refresh the list for everyone?
thanks!

**Comment by ghost** [comment]
FLAC support is on the to-do list since the project start.
Please be patient, but this takes a while.

**Please, don't mix up more than one bug or request in one issue. Thanks.**

**Comment by Rello** [comment]
followup in Roadmap
will be reopened when work is started

**Comment by microcreators** [comment]
Just to add to it... It sounds like the upcoming Chrome 56 would support FLAC streaming out of the box. Same for FF 51 (although I may be wrong here).

**Comment by SharkyRawr** [comment]
FLAC support has landed in Fx and Chrome. Knowing nothing about the internal workings of this project, could it now be as easy as adding the FLAC mime-type and/or extension to the list of supported formats?

**Comment by Rello** [comment]
Hello,
thank you for the heads-up.
we are following @scottschiller on this topic already and it seem promising to have something in the near future.
But its not only about the player - we need to tweak the scanner a little in regards to the big file sizes on external storage.

Keep on watching here

**Comment by Rello** [comment]
https://github.com/scottschiller/SoundManager2/issues/148

**Comment by Rello** [comment]
Hello,

the FLAC mime type is being integrated into Audio Player.
Attention: flac is only supported on latest Chrome & FF at the moment.

- [x] locally patch soundmanager2 due to missing update
- [x] Include in scanner
- [x] Include in files app (one click play & share player)
- [x] playlists depending on browser capabilities: When a browser is not able to play flac (or one of the others), the track will be marked with a different text formatting and an indicator is shown
- [x] display browser capabilities in user settings screen
- [x] create wiki for browser dependencies 
https://github.com/rello/audioplayer/wiki/audio-files-and-mime-types#browser-support

**Comment by Rello** [comment]
@xraMsamohT => Test
