### ISSUE TITLE
Feature request: navigation as in a real directory tree

### ISSUE THREAD

**Issue by DEvil0000** [Rello/audioplayer#469]
I have about 20GB music on my cloud but the metadata is missing or not very correct for most so all the navigation does not work well for me.
I however have sorted it in folders by type, subfolders for artists and subfolders for album. A navigation which would work as a more regular old directory navigation would be perfect.
Could be a directory tree view on the left or a folder wise navigation in the main panel.

**Comment by Rello** [comment]
Hello,
I got the request already some times.
The issue here:
everything is based on the music collection - in your case a lot of titles.
The list of metadata is being transferred to the frontend. in includes the parent folder (this his how the "folder" category works).

in your case, it would need to recursively iterate over the folder tree to finde the correct position and show it there. 
I did not find a clever way to do it - yet. still thinking about it.

One idea that just came into my mind:
separate the tree from the metadata.
one task would be to get the "whole" folder tree from the NC backend and display it in the navigation bar. once a folder is clicked, the filter is applied to the list.

I need to think about this a bit
Do you know any app where something is being displayed in a hierarchy view?

**Comment by DEvil0000** [comment]
For the implementation you may store the path up to the audio root instead just the parent folder.

I do not know any nextcloud app showing a hierarchy but there are a lot of multimedia web players or dlna/upnp servers doing so. I am for example used to this from my old QNAP where all the apps (musik, video, image - station/gallery) had such a view.

**Comment by Rello** [comment]
Hello,
I will close this old topic due to limited resources.
this implementation would be pretty expensive as it would hack Nextclouds standard way of the navigation window
