### ISSUE TITLE
case on tags

### ISSUE THREAD

**Issue by hboetes** [Rello/audioplayer#470]
I have quite a few files of which the case of the band is not consistent.

For example:
- Bob Marley and the Wailers
- Bob Marley And The Wailers
- Bob Marley & The Wailers

Could you group them in one and the Same band name?

Or for instance:
- The Eels
- Eels, the

**Comment by Rello** [comment]
Hallo,

AP is purely dependent on the quality of your ID3 data. The artist is a free-text field and it´s content is indexed and written to the DB. 
I don´t see any usefull way to modify/harmonize the data during indexing because the efforts would be huge for all languages.

I only see the chance to clean up the ID3 data there
