### ISSUE TITLE
[Feature Request] Audiobook Support

### ISSUE THREAD

**Issue by lemonlim3** [Rello/audioplayer#534]
Would be nice to have support for Audiobooks (ie allowing an option to save your place per audio file). This could also be an option per folder for easier management.

**Comment by Rello** [comment]
Hello,

AP saves the position of the last played file and should reopen at that position after the next start. 
does this work for you?

**Comment by r4sas** [comment]
He means about saving playtime for all files.

**Comment by Rello** [comment]
Hi,
I am thinking about it. currently, the value is stored as one value in the user parameters.
To match the request, it would require a whole new database table to store the playcount per user/title.

But the challenge is: when to store the value and when not?
store for every file is not really useful because it would drive you crazy when every file would start at a different position.

What would you suggest? any ideas?
or hints from other apps?

**Comment by lemonlim3** [comment]
How I envision it would be adding an option in the left click menu on all audio files that would need to be manually enabled to save your spot, and adding the same option for folders that would apply to all audio files within that folder / subfolders. How to accomplish that is beyond me but that's the best solution that comes to mind.

**Comment by progressify** [comment]
I am interested too in this feature

**Comment by kitzler-walli** [comment]
Saving the position for every playlist/smartlist/folder would probably be a good idea, and save which of these was played last. I currently plan to build additional apps for echo and ios to allow audiobook playback from nextcloud, based on audioplayer. 
My goal is to simply shout "play my audiobook" whether it's Alexa, Siri or any other client and be able to listen to my current book at the position last saved from the last device I was listening on.

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.
