### ISSUE TITLE
[Feature Request] Make possible to create a queue of songs

### ISSUE THREAD

**Issue by pyccino** [Rello/audioplayer#536]
Hi, an idea to improve this app would be to make it possible to add a song to a queue.Like is already done by spotify or apple music.
 I think that the best solution would be to add a 2-list drop down menu when you click the three dots next to a song. One of which could display "details" and the other "add to queue".

**Comment by Rello** [comment]
Hello,
interesting idea. should actually work because the actual list to be played is a second one in the background - do enable browsing while playing one album.

just need to think how to do it. what would you expect?

- if you directly click on a title within an album e.g. the list is cleared and the album is put in the "queue".
- via the "add to queue" you would add it at the end or as the next title?
- if you klick a regular title of an album, the queue would be reset to that album again?

**Comment by pyccino** [comment]
I'm so sorry for the late reply.
personally i would make a setting to make it persoizable to the user (since everyone has different opinion on this) 
but for started i would use the first option.

**Comment by philus88** [comment]
i would also like to such a feature. "add to current queue"
in addition to this is there a way to view the actual queue when you hit play on a folder level ? - this would be great too.

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.
