### ISSUE TITLE
Scan of smb mount stalls at 192 entries

### ISSUE THREAD

**Issue by c3dub** [Rello/audioplayer#69]
### Expected behavior

Complete scan of music library
### Actual behavior

Scan for audio files stalls at 0% (192/45446).  When viewing the scanned files by 'Artist' many artists only have 1 song listed even though there may be a number of albums with many songs on the server; however a few have more than one song. See attached screen shot.
![screen shot 2016-10-15 at 1 29 54 pm](https://cloud.githubusercontent.com/assets/2858731/19413206/aea8741a-92db-11e6-991b-f5b8bd6e8c09.png)
### Steps to reproduce the behavior
1. Login to NextCloud 10.0.1 using OS X 10.11 with Safari, Chrome or Firefox
2. Select Audio Player app
3. Click (double arrow) Scan for new audio files and initiate scan
4. After a few seconds the scan stalls and does not complete.
### Server configuration

**Operating system**:
Debian 8 Jessie [3.16.0-4-amd64]

**Web server:**
Apache/2.4.10 (Debian)

**Database:**
mariadb-server-10.0            10.0.27-0+deb8u1 

**PHP version:**
PHP 5.6.26-0+deb8u1

**ownCloud/Nextcloud version:** (see `/status.php`)
Nextcloud 10.0.1 stable

**Updated from an older ownCloud/Nextcloud or fresh install:**
Migrated from Owncloud 9.02 stable

**Where did you install Audio Player from:**
Download from github

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
Yes.  SMB/CIFS

**Are you using encryption:** yes/no
No
### Client configuration

**Operating system:**
OS X 10.11.6

**Browser:**
Safari 10.0
Chrome Version 53.0.2785.143 (64-bit)
Firefox 48.0.2
### Log

<details>
<summary>

ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>

```
locate nextcloud.log finds no matches. 

No errors reported in apache2 error.log and nothing seems problematic in the access.log

```

</details>

**Comment by Rello** [comment]
Hello @c3dub ,
there needs to be some info in the nextcloud/owncloud.log.
Either NC broke because some wrong input or php broke because of something else.

does it always fail at the same point, even if you restart the scan again and again (without resetting the library)? because then it should continue where it stopped.

let me know...

**Comment by c3dub** [comment]
Hi Rello,

Every time I check for new files it is the same 0% (0/45446) runs for ten -15 seconds and then stalls at 0% (192/45446).

Rebooted server and client and started fresh, same issue. Here are the pertinent lines from the nextcloud log.  It reports an error with a jpg file.  

[nextcloud.txt](https://github.com/Rello/audioplayer/files/531943/nextcloud.txt)

The quick fix: How does one identify which file is causing the error so it can be fixed/deleted?  

Longer term: It would be nice if the error was reported but indexing continued to completion.

**Comment by Rello** [comment]
That helped!
It is the same as #57
There is an issue in the core imho. But i will try to implement something on my own. 

Keymessage: one cover art is that corrupt, that php csn not handle it. 

I will keep you posted

**Comment by Rello** [comment]
@c3dub 
sorry for the late reply. it took some time to figure out how to handle this.
I installed an error handler which will log the file in worst case to OC/NC.log for further analysis.
continuing will not be possible in this case because its a "fatal error" and there is no chance to recover from.

do you have the chance to manually download the modified file `controller/scannercontroller.php`
and give it a try in your installation?
the change is shown here: https://github.com/Rello/audioplayer/commit/ff776bec9188fabf31d7dbd0f0dbb7892a0166f2

thank you for your help

**Comment by c3dub** [comment]
Hi Rello,

Thanks for the update.  I installed the updated controller/scannercontroller.php file, deleted the nextcloud.log file, and then started a scan.  The scan stalled at 192 files again.  When I open nextcloud.log this is what is recorded there:

```
{"reqId":"5zu0Y8AlJoWGN28OAQTo","remoteAddr":"my_ip_address","app":"PHP","message":"imagecreatefromstring(): gd-jpeg: JPEG library reports unrecoverable error: Invalid JPEG file structure: two SOI markers at /var/www/ssl/nextcloud/lib/private/legacy/image.php#598","level":3,"time":"2016-10-21T00:08:43+00:00","method":"POST","url":"/nextcloud/index.php/apps/audioplayer/scanforaudiofiles","user":"my_userid"}
```

Thanks,
c3dub

**Comment by Rello** [comment]
Hello @c3dub 

thank you for your feedback. So my suggested idea did not work because I was not able to reproduce the exact issue.
I followed another approach now and updated the behavior of the progress bar.
It will show the file currently being progressed. whenever the scanner stops, the file being shown should be the one making problems (logfile for the details of the problems).

could you give the updated scannercontroller another try?
thank you for your patience,
let me know

**Comment by c3dub** [comment]
Hi Rello,

This solved my problem.  Thank you!!  

As described when the problem file was encountered the name of the file was displayed.  I edited this file in iTunes to remove the embedded artwork, saved the file, and started a new scan  - which is now at 2000 files and still going.

c3dub

**Comment by Rello** [comment]
nice to hear.
thank you
