### ISSUE TITLE
Configurable album sorting order

### ISSUE THREAD

**Issue by kernel1024** [Rello/audioplayer#86]
Just small feature request, related to #80 . It would be cool, if sort field can be configured from gui for albums list. 

As an addition, clementine media player (and old amarok 1.x) has 3-level sorting, selectable from 'category selector' combobox (e.g. Genre/Album, Genre/Artist/Album, Artist/Album, Artist/Year/Album). This is very useful feature for big collections too.

**Comment by ghost** [comment]
@kernel1024 It's not what you requested, but we have added `Albums` to the selection #132 and sorting of lists #122 . The list view will be enhanced in the next versions with more columns (tags). In the meantime I close the issue because we will not enhance the category selector by more levels or change the album view with covers in the near future (not in this major version).
You may test the `Beta 3` or wait for the upcoming release.
